org: kev123
service: pdf-generator

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::node-craft/*"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /generate
          method: post